# Generated by Django 3.2.1 on 2021-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_remove_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/',
                                    verbose_name='Изображение'),
        ),
    ]
