# Generated by Django 3.2.1 on 2021-05-11 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now,
                                   unique=True, verbose_name='Уникальный URL'),
            preserve_default=False,
        ),
    ]
