# Generated by Django 3.2.1 on 2021-05-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0008_auto_20210511_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipe_ingredient', to='recipes.recipe',
                verbose_name='Рецепт'),
        ),
    ]
